$(document).ready(function(){	
	$(".aide").hide();
	$(".description").click(function(event){
		console.log("click");
		console.log($(".this"));
		//$("#aide").hide();
		$("this").find(".aide").show("slow");
	});
});